18/01/08 08:55:45 [INFO] 285 Start server. [127.0.0.1:9999]
18/01/08 08:56:53 [INFO] 41 [('127.0.0.1', 49601)] ('127.0.0.1', 49601) is connected.
18/01/08 08:56:53 [INFO] 45 [('127.0.0.1', 49601)] Account: user02
18/01/08 08:56:53 [WARNING] 57 [('127.0.0.1', 49601)] "user02" Auth failed.
18/01/08 08:56:53 [WARNING] 125 [('127.0.0.1', 49601)] ('127.0.0.1', 49601) is disconnected.
18/01/08 08:56:56 [INFO] 41 [('127.0.0.1', 49602)] ('127.0.0.1', 49602) is connected.
18/01/08 08:56:56 [INFO] 45 [('127.0.0.1', 49602)] Account: user02
18/01/08 08:56:56 [INFO] 60 [('127.0.0.1', 49602)] "user02" Auth success.
18/01/08 08:56:57 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'3'
18/01/08 08:56:57 [INFO] 88 [('127.0.0.1', 49602)] Command: dir
18/01/08 08:56:57 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _dir
18/01/08 08:57:00 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'13'
18/01/08 08:57:00 [INFO] 88 [('127.0.0.1', 49602)] Command: cd sub_user02
18/01/08 08:57:00 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _cd
18/01/08 08:57:00 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'3'
18/01/08 08:57:00 [INFO] 88 [('127.0.0.1', 49602)] Command: dir
18/01/08 08:57:00 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _dir
18/01/08 08:57:05 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'10'
18/01/08 08:57:05 [INFO] 88 [('127.0.0.1', 49602)] Command: put 01.mp4 6475147
18/01/08 08:57:05 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _put
18/01/08 08:57:07 [INFO] 172 [('127.0.0.1', 49602)] File md5 value is correct. [01.mp4]
18/01/08 08:58:02 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'3'
18/01/08 08:58:02 [INFO] 88 [('127.0.0.1', 49602)] Command: dir
18/01/08 08:58:02 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _dir
18/01/08 08:58:05 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'10'
18/01/08 08:58:05 [INFO] 88 [('127.0.0.1', 49602)] Command: get 01.mp4
18/01/08 08:58:05 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _get
18/01/08 08:58:07 [INFO] 194 [('127.0.0.1', 49602)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:06:48 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'3'
18/01/08 09:06:48 [INFO] 88 [('127.0.0.1', 49602)] Command: dir
18/01/08 09:06:48 [DEBUG] 102 [('127.0.0.1', 49602)] Action: _dir
18/01/08 09:06:48 [DEBUG] 75 [('127.0.0.1', 49602)] Recive data length: b'3'
18/01/08 09:06:49 [INFO] 88 [('127.0.0.1', 49602)] Command: 
18/01/08 09:06:49 [ERROR] 92 [('127.0.0.1', 49602)] list index out of range
18/01/08 09:06:49 [WARNING] 125 [('127.0.0.1', 49602)] ('127.0.0.1', 49602) is disconnected.
18/01/08 09:06:52 [INFO] 41 [('127.0.0.1', 49687)] ('127.0.0.1', 49687) is connected.
18/01/08 09:06:52 [INFO] 45 [('127.0.0.1', 49687)] Account: user02
18/01/08 09:06:52 [WARNING] 57 [('127.0.0.1', 49687)] "user02" Auth failed.
18/01/08 09:06:52 [WARNING] 125 [('127.0.0.1', 49687)] ('127.0.0.1', 49687) is disconnected.
18/01/08 09:06:54 [INFO] 41 [('127.0.0.1', 49688)] ('127.0.0.1', 49688) is connected.
18/01/08 09:06:54 [INFO] 45 [('127.0.0.1', 49688)] Account: user02
18/01/08 09:06:54 [INFO] 60 [('127.0.0.1', 49688)] "user02" Auth success.
18/01/08 09:06:55 [DEBUG] 75 [('127.0.0.1', 49688)] Recive data length: b'3'
18/01/08 09:06:55 [INFO] 88 [('127.0.0.1', 49688)] Command: dir
18/01/08 09:06:55 [DEBUG] 102 [('127.0.0.1', 49688)] Action: _dir
18/01/08 09:06:58 [DEBUG] 75 [('127.0.0.1', 49688)] Recive data length: b'13'
18/01/08 09:06:58 [INFO] 88 [('127.0.0.1', 49688)] Command: cd sub_user02
18/01/08 09:06:58 [DEBUG] 102 [('127.0.0.1', 49688)] Action: _cd
18/01/08 09:06:58 [DEBUG] 75 [('127.0.0.1', 49688)] Recive data length: b'3'
18/01/08 09:06:58 [INFO] 88 [('127.0.0.1', 49688)] Command: dir
18/01/08 09:06:58 [DEBUG] 102 [('127.0.0.1', 49688)] Action: _dir
18/01/08 09:07:02 [DEBUG] 75 [('127.0.0.1', 49688)] Recive data length: b'10'
18/01/08 09:07:02 [INFO] 88 [('127.0.0.1', 49688)] Command: get 01.mp4
18/01/08 09:07:02 [DEBUG] 102 [('127.0.0.1', 49688)] Action: _get
18/01/08 09:07:04 [INFO] 194 [('127.0.0.1', 49688)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:07:24 [DEBUG] 75 [('127.0.0.1', 49688)] Recive data length: b'3'
18/01/08 09:07:24 [INFO] 88 [('127.0.0.1', 49688)] Command: 
18/01/08 09:07:24 [ERROR] 92 [('127.0.0.1', 49688)] list index out of range
18/01/08 09:07:24 [WARNING] 125 [('127.0.0.1', 49688)] ('127.0.0.1', 49688) is disconnected.
18/01/08 09:07:26 [INFO] 41 [('127.0.0.1', 49689)] ('127.0.0.1', 49689) is connected.
18/01/08 09:07:26 [INFO] 45 [('127.0.0.1', 49689)] Account: user02
18/01/08 09:07:26 [INFO] 60 [('127.0.0.1', 49689)] "user02" Auth success.
18/01/08 09:07:28 [DEBUG] 75 [('127.0.0.1', 49689)] Recive data length: b'10'
18/01/08 09:07:28 [INFO] 88 [('127.0.0.1', 49689)] Command: get 01.mp4
18/01/08 09:07:28 [DEBUG] 102 [('127.0.0.1', 49689)] Action: _get
18/01/08 09:07:32 [DEBUG] 75 [('127.0.0.1', 49689)] Recive data length: b'13'
18/01/08 09:07:32 [INFO] 88 [('127.0.0.1', 49689)] Command: cd sub_user02
18/01/08 09:07:32 [DEBUG] 102 [('127.0.0.1', 49689)] Action: _cd
18/01/08 09:07:33 [DEBUG] 75 [('127.0.0.1', 49689)] Recive data length: b'3'
18/01/08 09:07:33 [INFO] 88 [('127.0.0.1', 49689)] Command: dir
18/01/08 09:07:33 [DEBUG] 102 [('127.0.0.1', 49689)] Action: _dir
18/01/08 09:07:36 [DEBUG] 75 [('127.0.0.1', 49689)] Recive data length: b'10'
18/01/08 09:07:36 [INFO] 88 [('127.0.0.1', 49689)] Command: get 01.mp4
18/01/08 09:07:36 [DEBUG] 102 [('127.0.0.1', 49689)] Action: _get
18/01/08 09:07:36 [INFO] 194 [('127.0.0.1', 49689)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:09:02 [DEBUG] 75 [('127.0.0.1', 49689)] Recive data length: b'3'
18/01/08 09:09:02 [INFO] 88 [('127.0.0.1', 49689)] Command: 
18/01/08 09:09:02 [ERROR] 92 [('127.0.0.1', 49689)] list index out of range
18/01/08 09:09:02 [WARNING] 125 [('127.0.0.1', 49689)] ('127.0.0.1', 49689) is disconnected.
18/01/08 09:09:26 [INFO] 282 Start server. [127.0.0.1:9999]
18/01/08 09:09:33 [INFO] 41 [('127.0.0.1', 49697)] ('127.0.0.1', 49697) is connected.
18/01/08 09:09:33 [INFO] 45 [('127.0.0.1', 49697)] Account: user02
18/01/08 09:09:33 [INFO] 60 [('127.0.0.1', 49697)] "user02" Auth success.
18/01/08 09:09:36 [DEBUG] 75 [('127.0.0.1', 49697)] Recive data length: b'10'
18/01/08 09:09:36 [INFO] 88 [('127.0.0.1', 49697)] Command: get 01.mp4
18/01/08 09:09:36 [DEBUG] 102 [('127.0.0.1', 49697)] Action: _get
18/01/08 09:09:39 [DEBUG] 75 [('127.0.0.1', 49697)] Recive data length: b'13'
18/01/08 09:09:39 [INFO] 88 [('127.0.0.1', 49697)] Command: cd sub_user02
18/01/08 09:09:39 [DEBUG] 102 [('127.0.0.1', 49697)] Action: _cd
18/01/08 09:09:40 [DEBUG] 75 [('127.0.0.1', 49697)] Recive data length: b'3'
18/01/08 09:09:40 [INFO] 88 [('127.0.0.1', 49697)] Command: dir
18/01/08 09:09:40 [DEBUG] 102 [('127.0.0.1', 49697)] Action: _dir
18/01/08 09:09:42 [DEBUG] 75 [('127.0.0.1', 49697)] Recive data length: b'10'
18/01/08 09:09:42 [INFO] 88 [('127.0.0.1', 49697)] Command: get 01.mp4
18/01/08 09:09:42 [DEBUG] 102 [('127.0.0.1', 49697)] Action: _get
18/01/08 09:09:42 [INFO] 191 [('127.0.0.1', 49697)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:09:48 [DEBUG] 75 [('127.0.0.1', 49697)] Recive data length: b'3'
18/01/08 09:09:48 [INFO] 88 [('127.0.0.1', 49697)] Command: 
18/01/08 09:09:48 [ERROR] 92 [('127.0.0.1', 49697)] list index out of range
18/01/08 09:09:48 [WARNING] 125 [('127.0.0.1', 49697)] ('127.0.0.1', 49697) is disconnected.
18/01/08 09:11:48 [INFO] 41 [('127.0.0.1', 49703)] ('127.0.0.1', 49703) is connected.
18/01/08 09:11:48 [INFO] 45 [('127.0.0.1', 49703)] Account: user02
18/01/08 09:11:48 [INFO] 60 [('127.0.0.1', 49703)] "user02" Auth success.
18/01/08 09:11:50 [DEBUG] 75 [('127.0.0.1', 49703)] Recive data length: b'3'
18/01/08 09:11:50 [INFO] 88 [('127.0.0.1', 49703)] Command: dir
18/01/08 09:11:50 [DEBUG] 102 [('127.0.0.1', 49703)] Action: _dir
18/01/08 09:11:54 [DEBUG] 75 [('127.0.0.1', 49703)] Recive data length: b'13'
18/01/08 09:11:54 [INFO] 88 [('127.0.0.1', 49703)] Command: cd sub_user02
18/01/08 09:11:54 [DEBUG] 102 [('127.0.0.1', 49703)] Action: _cd
18/01/08 09:11:54 [DEBUG] 75 [('127.0.0.1', 49703)] Recive data length: b'3'
18/01/08 09:11:54 [INFO] 88 [('127.0.0.1', 49703)] Command: dir
18/01/08 09:11:54 [DEBUG] 102 [('127.0.0.1', 49703)] Action: _dir
18/01/08 09:11:56 [DEBUG] 75 [('127.0.0.1', 49703)] Recive data length: b'10'
18/01/08 09:11:56 [INFO] 88 [('127.0.0.1', 49703)] Command: get 01.mp4
18/01/08 09:11:56 [DEBUG] 102 [('127.0.0.1', 49703)] Action: _get
18/01/08 09:11:58 [INFO] 191 [('127.0.0.1', 49703)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:14:21 [WARNING] 125 [('127.0.0.1', 49703)] ('127.0.0.1', 49703) is disconnected.
18/01/08 09:14:25 [INFO] 41 [('127.0.0.1', 49707)] ('127.0.0.1', 49707) is connected.
18/01/08 09:14:25 [INFO] 45 [('127.0.0.1', 49707)] Account: user02
18/01/08 09:14:25 [INFO] 60 [('127.0.0.1', 49707)] "user02" Auth success.
18/01/08 09:14:25 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'3'
18/01/08 09:14:25 [INFO] 88 [('127.0.0.1', 49707)] Command: dir
18/01/08 09:14:25 [DEBUG] 102 [('127.0.0.1', 49707)] Action: _dir
18/01/08 09:14:29 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'13'
18/01/08 09:14:29 [INFO] 88 [('127.0.0.1', 49707)] Command: cd sub_user02
18/01/08 09:14:29 [DEBUG] 102 [('127.0.0.1', 49707)] Action: _cd
18/01/08 09:14:30 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'3'
18/01/08 09:14:30 [INFO] 88 [('127.0.0.1', 49707)] Command: dir
18/01/08 09:14:30 [DEBUG] 102 [('127.0.0.1', 49707)] Action: _dir
18/01/08 09:14:32 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'10'
18/01/08 09:14:32 [INFO] 88 [('127.0.0.1', 49707)] Command: get 01.mp4
18/01/08 09:14:32 [DEBUG] 102 [('127.0.0.1', 49707)] Action: _get
18/01/08 09:14:32 [INFO] 191 [('127.0.0.1', 49707)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:14:43 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'10'
18/01/08 09:14:43 [INFO] 88 [('127.0.0.1', 49707)] Command: get 01.mp4
18/01/08 09:14:43 [DEBUG] 102 [('127.0.0.1', 49707)] Action: _get
18/01/08 09:14:44 [INFO] 191 [('127.0.0.1', 49707)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:15:21 [DEBUG] 75 [('127.0.0.1', 49707)] Recive data length: b'3'
18/01/08 09:15:21 [INFO] 88 [('127.0.0.1', 49707)] Command: 
18/01/08 09:15:21 [ERROR] 92 [('127.0.0.1', 49707)] list index out of range
18/01/08 09:15:21 [WARNING] 125 [('127.0.0.1', 49707)] ('127.0.0.1', 49707) is disconnected.
18/01/08 09:15:36 [INFO] 41 [('127.0.0.1', 49709)] ('127.0.0.1', 49709) is connected.
18/01/08 09:15:36 [INFO] 45 [('127.0.0.1', 49709)] Account: user02
18/01/08 09:15:36 [INFO] 60 [('127.0.0.1', 49709)] "user02" Auth success.
18/01/08 09:15:36 [DEBUG] 75 [('127.0.0.1', 49709)] Recive data length: b'3'
18/01/08 09:15:36 [INFO] 88 [('127.0.0.1', 49709)] Command: dir
18/01/08 09:15:36 [DEBUG] 102 [('127.0.0.1', 49709)] Action: _dir
18/01/08 09:15:39 [DEBUG] 75 [('127.0.0.1', 49709)] Recive data length: b'13'
18/01/08 09:15:39 [INFO] 88 [('127.0.0.1', 49709)] Command: cd sub_user02
18/01/08 09:15:39 [DEBUG] 102 [('127.0.0.1', 49709)] Action: _cd
18/01/08 09:15:39 [DEBUG] 75 [('127.0.0.1', 49709)] Recive data length: b'3'
18/01/08 09:15:39 [INFO] 88 [('127.0.0.1', 49709)] Command: dir
18/01/08 09:15:39 [DEBUG] 102 [('127.0.0.1', 49709)] Action: _dir
18/01/08 09:15:41 [DEBUG] 75 [('127.0.0.1', 49709)] Recive data length: b'10'
18/01/08 09:15:41 [INFO] 88 [('127.0.0.1', 49709)] Command: get 01.mp4
18/01/08 09:15:41 [DEBUG] 102 [('127.0.0.1', 49709)] Action: _get
18/01/08 09:15:43 [INFO] 191 [('127.0.0.1', 49709)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:15:57 [DEBUG] 75 [('127.0.0.1', 49709)] Recive data length: b'3'
18/01/08 09:15:57 [INFO] 88 [('127.0.0.1', 49709)] Command: 
18/01/08 09:15:57 [ERROR] 92 [('127.0.0.1', 49709)] list index out of range
18/01/08 09:15:57 [WARNING] 125 [('127.0.0.1', 49709)] ('127.0.0.1', 49709) is disconnected.
18/01/08 09:16:03 [INFO] 41 [('127.0.0.1', 49724)] ('127.0.0.1', 49724) is connected.
18/01/08 09:16:03 [INFO] 45 [('127.0.0.1', 49724)] Account: user02
18/01/08 09:16:03 [INFO] 60 [('127.0.0.1', 49724)] "user02" Auth success.
18/01/08 09:16:04 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'3'
18/01/08 09:16:04 [INFO] 88 [('127.0.0.1', 49724)] Command: dir
18/01/08 09:16:04 [DEBUG] 102 [('127.0.0.1', 49724)] Action: _dir
18/01/08 09:16:14 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'13'
18/01/08 09:16:14 [INFO] 88 [('127.0.0.1', 49724)] Command: cd sub_user02
18/01/08 09:16:14 [DEBUG] 102 [('127.0.0.1', 49724)] Action: _cd
18/01/08 09:16:15 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'3'
18/01/08 09:16:15 [INFO] 88 [('127.0.0.1', 49724)] Command: dir
18/01/08 09:16:15 [DEBUG] 102 [('127.0.0.1', 49724)] Action: _dir
18/01/08 09:16:17 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'10'
18/01/08 09:16:17 [INFO] 88 [('127.0.0.1', 49724)] Command: get 01.mp4
18/01/08 09:16:17 [DEBUG] 102 [('127.0.0.1', 49724)] Action: _get
18/01/08 09:16:17 [INFO] 191 [('127.0.0.1', 49724)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:16:46 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'10'
18/01/08 09:16:46 [INFO] 88 [('127.0.0.1', 49724)] Command: get 01.mp4
18/01/08 09:16:46 [DEBUG] 102 [('127.0.0.1', 49724)] Action: _get
18/01/08 09:16:48 [INFO] 191 [('127.0.0.1', 49724)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:16:53 [DEBUG] 75 [('127.0.0.1', 49724)] Recive data length: b'3'
18/01/08 09:16:53 [INFO] 88 [('127.0.0.1', 49724)] Command: 
18/01/08 09:16:53 [ERROR] 92 [('127.0.0.1', 49724)] list index out of range
18/01/08 09:16:53 [WARNING] 125 [('127.0.0.1', 49724)] ('127.0.0.1', 49724) is disconnected.
18/01/08 09:17:25 [INFO] 41 [('127.0.0.1', 49734)] ('127.0.0.1', 49734) is connected.
18/01/08 09:17:25 [INFO] 45 [('127.0.0.1', 49734)] Account: user02
18/01/08 09:17:25 [INFO] 60 [('127.0.0.1', 49734)] "user02" Auth success.
18/01/08 09:17:25 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'3'
18/01/08 09:17:25 [INFO] 88 [('127.0.0.1', 49734)] Command: dir
18/01/08 09:17:25 [DEBUG] 102 [('127.0.0.1', 49734)] Action: _dir
18/01/08 09:17:27 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'13'
18/01/08 09:17:27 [INFO] 88 [('127.0.0.1', 49734)] Command: cd sub_user02
18/01/08 09:17:27 [DEBUG] 102 [('127.0.0.1', 49734)] Action: _cd
18/01/08 09:17:28 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'3'
18/01/08 09:17:28 [INFO] 88 [('127.0.0.1', 49734)] Command: dir
18/01/08 09:17:28 [DEBUG] 102 [('127.0.0.1', 49734)] Action: _dir
18/01/08 09:17:40 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'10'
18/01/08 09:17:40 [INFO] 88 [('127.0.0.1', 49734)] Command: get 01.mp4
18/01/08 09:17:40 [DEBUG] 102 [('127.0.0.1', 49734)] Action: _get
18/01/08 09:17:41 [INFO] 191 [('127.0.0.1', 49734)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4" complete.
18/01/08 09:17:45 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'3'
18/01/08 09:17:45 [INFO] 88 [('127.0.0.1', 49734)] Command: dir
18/01/08 09:17:45 [DEBUG] 102 [('127.0.0.1', 49734)] Action: _dir
18/01/08 09:17:49 [DEBUG] 75 [('127.0.0.1', 49734)] Recive data length: b'3'
18/01/08 09:17:49 [INFO] 88 [('127.0.0.1', 49734)] Command: 
18/01/08 09:17:49 [ERROR] 92 [('127.0.0.1', 49734)] list index out of range
18/01/08 09:17:49 [WARNING] 125 [('127.0.0.1', 49734)] ('127.0.0.1', 49734) is disconnected.
18/01/08 09:18:04 [INFO] 41 [('127.0.0.1', 49735)] ('127.0.0.1', 49735) is connected.
18/01/08 09:18:04 [INFO] 45 [('127.0.0.1', 49735)] Account: user02
18/01/08 09:18:04 [INFO] 60 [('127.0.0.1', 49735)] "user02" Auth success.
18/01/08 09:18:05 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:18:05 [INFO] 88 [('127.0.0.1', 49735)] Command: dir
18/01/08 09:18:05 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _dir
18/01/08 09:18:07 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'13'
18/01/08 09:18:07 [INFO] 88 [('127.0.0.1', 49735)] Command: cd sub_user02
18/01/08 09:18:07 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _cd
18/01/08 09:18:08 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:18:08 [INFO] 88 [('127.0.0.1', 49735)] Command: dir
18/01/08 09:18:08 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _dir
18/01/08 09:18:11 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'10'
18/01/08 09:18:11 [INFO] 88 [('127.0.0.1', 49735)] Command: del 01.mp4
18/01/08 09:18:11 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _del
18/01/08 09:18:11 [DEBUG] 262 [('127.0.0.1', 49735)] Delete success: D:\python_projects\training_bloke\module3\ftp\dirs\user02\sub_user02\01.mp4
18/01/08 09:18:11 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:18:11 [INFO] 88 [('127.0.0.1', 49735)] Command: dir
18/01/08 09:18:11 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _dir
18/01/08 09:18:12 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'5'
18/01/08 09:18:12 [INFO] 88 [('127.0.0.1', 49735)] Command: cd ..
18/01/08 09:18:12 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _cd
18/01/08 09:18:12 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:18:12 [INFO] 88 [('127.0.0.1', 49735)] Command: dir
18/01/08 09:18:12 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _dir
18/01/08 09:23:22 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:23:22 [INFO] 88 [('127.0.0.1', 49735)] Command: dir
18/01/08 09:23:22 [DEBUG] 102 [('127.0.0.1', 49735)] Action: _dir
18/01/08 09:23:24 [DEBUG] 75 [('127.0.0.1', 49735)] Recive data length: b'3'
18/01/08 09:23:24 [INFO] 88 [('127.0.0.1', 49735)] Command: 
18/01/08 09:23:24 [ERROR] 92 [('127.0.0.1', 49735)] list index out of range
18/01/08 09:23:24 [WARNING] 125 [('127.0.0.1', 49735)] ('127.0.0.1', 49735) is disconnected.
18/01/08 09:23:36 [INFO] 41 [('127.0.0.1', 49737)] ('127.0.0.1', 49737) is connected.
18/01/08 09:23:36 [INFO] 45 [('127.0.0.1', 49737)] Account: user02
18/01/08 09:23:36 [INFO] 60 [('127.0.0.1', 49737)] "user02" Auth success.
18/01/08 09:23:36 [DEBUG] 75 [('127.0.0.1', 49737)] Recive data length: b'3'
18/01/08 09:23:36 [INFO] 88 [('127.0.0.1', 49737)] Command: dir
18/01/08 09:23:36 [DEBUG] 102 [('127.0.0.1', 49737)] Action: _dir
18/01/08 09:23:39 [DEBUG] 75 [('127.0.0.1', 49737)] Recive data length: b'26'
18/01/08 09:23:39 [INFO] 88 [('127.0.0.1', 49737)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:23:39 [DEBUG] 102 [('127.0.0.1', 49737)] Action: _put
18/01/08 09:23:39 [WARNING] 125 [('127.0.0.1', 49737)] ('127.0.0.1', 49737) is disconnected.
18/01/08 09:24:47 [INFO] 41 [('127.0.0.1', 49738)] ('127.0.0.1', 49738) is connected.
18/01/08 09:24:47 [INFO] 45 [('127.0.0.1', 49738)] Account: user02
18/01/08 09:24:47 [INFO] 60 [('127.0.0.1', 49738)] "user02" Auth success.
18/01/08 09:24:50 [DEBUG] 75 [('127.0.0.1', 49738)] Recive data length: b'26'
18/01/08 09:24:50 [INFO] 88 [('127.0.0.1', 49738)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:24:50 [DEBUG] 102 [('127.0.0.1', 49738)] Action: _put
18/01/08 09:25:05 [INFO] 169 [('127.0.0.1', 49738)] File md5 value is correct. [python-3.6.3-amd64.exe]
18/01/08 09:25:25 [DEBUG] 75 [('127.0.0.1', 49738)] Recive data length: b'3'
18/01/08 09:25:25 [INFO] 88 [('127.0.0.1', 49738)] Command: dir
18/01/08 09:25:25 [DEBUG] 102 [('127.0.0.1', 49738)] Action: _dir
18/01/08 09:25:30 [DEBUG] 75 [('127.0.0.1', 49738)] Recive data length: b'26'
18/01/08 09:25:30 [INFO] 88 [('127.0.0.1', 49738)] Command: del python-3.6.3-amd64.exe
18/01/08 09:25:30 [DEBUG] 102 [('127.0.0.1', 49738)] Action: _del
18/01/08 09:25:30 [DEBUG] 262 [('127.0.0.1', 49738)] Delete success: D:\python_projects\training_bloke\module3\ftp\dirs\user02\python-3.6.3-amd64.exe
18/01/08 09:25:31 [DEBUG] 75 [('127.0.0.1', 49738)] Recive data length: b'3'
18/01/08 09:25:31 [INFO] 88 [('127.0.0.1', 49738)] Command: dir
18/01/08 09:25:31 [DEBUG] 102 [('127.0.0.1', 49738)] Action: _dir
18/01/08 09:25:32 [DEBUG] 75 [('127.0.0.1', 49738)] Recive data length: b'3'
18/01/08 09:25:32 [INFO] 88 [('127.0.0.1', 49738)] Command: 
18/01/08 09:25:32 [ERROR] 92 [('127.0.0.1', 49738)] list index out of range
18/01/08 09:25:32 [WARNING] 125 [('127.0.0.1', 49738)] ('127.0.0.1', 49738) is disconnected.
18/01/08 09:25:34 [INFO] 41 [('127.0.0.1', 49739)] ('127.0.0.1', 49739) is connected.
18/01/08 09:25:34 [INFO] 45 [('127.0.0.1', 49739)] Account: user02
18/01/08 09:25:34 [INFO] 60 [('127.0.0.1', 49739)] "user02" Auth success.
18/01/08 09:25:38 [DEBUG] 75 [('127.0.0.1', 49739)] Recive data length: b'26'
18/01/08 09:25:38 [INFO] 88 [('127.0.0.1', 49739)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:25:38 [DEBUG] 102 [('127.0.0.1', 49739)] Action: _put
18/01/08 09:25:54 [INFO] 169 [('127.0.0.1', 49739)] File md5 value is correct. [python-3.6.3-amd64.exe]
18/01/08 09:26:20 [DEBUG] 75 [('127.0.0.1', 49739)] Recive data length: b'3'
18/01/08 09:26:20 [INFO] 88 [('127.0.0.1', 49739)] Command: 
18/01/08 09:26:20 [ERROR] 92 [('127.0.0.1', 49739)] list index out of range
18/01/08 09:26:20 [WARNING] 125 [('127.0.0.1', 49739)] ('127.0.0.1', 49739) is disconnected.
18/01/08 09:26:24 [INFO] 41 [('127.0.0.1', 49740)] ('127.0.0.1', 49740) is connected.
18/01/08 09:26:24 [INFO] 45 [('127.0.0.1', 49740)] Account: user02
18/01/08 09:26:24 [INFO] 60 [('127.0.0.1', 49740)] "user02" Auth success.
18/01/08 09:26:25 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'3'
18/01/08 09:26:25 [INFO] 88 [('127.0.0.1', 49740)] Command: dir
18/01/08 09:26:25 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _dir
18/01/08 09:26:27 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'26'
18/01/08 09:26:27 [INFO] 88 [('127.0.0.1', 49740)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:26:27 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _put
18/01/08 09:26:27 [INFO] 169 [('127.0.0.1', 49740)] File md5 value is correct. [python-3.6.3-amd64.exe]
18/01/08 09:26:31 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'3'
18/01/08 09:26:31 [INFO] 88 [('127.0.0.1', 49740)] Command: dir
18/01/08 09:26:31 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _dir
18/01/08 09:26:34 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'26'
18/01/08 09:26:34 [INFO] 88 [('127.0.0.1', 49740)] Command: del python-3.6.3-amd64.exe
18/01/08 09:26:34 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _del
18/01/08 09:26:34 [DEBUG] 262 [('127.0.0.1', 49740)] Delete success: D:\python_projects\training_bloke\module3\ftp\dirs\user02\python-3.6.3-amd64.exe
18/01/08 09:26:34 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'3'
18/01/08 09:26:34 [INFO] 88 [('127.0.0.1', 49740)] Command: dir
18/01/08 09:26:34 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _dir
18/01/08 09:26:38 [DEBUG] 75 [('127.0.0.1', 49740)] Recive data length: b'26'
18/01/08 09:26:38 [INFO] 88 [('127.0.0.1', 49740)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:26:38 [DEBUG] 102 [('127.0.0.1', 49740)] Action: _put
18/01/08 09:26:44 [WARNING] 125 [('127.0.0.1', 49740)] ('127.0.0.1', 49740) is disconnected.
18/01/08 09:26:47 [INFO] 41 [('127.0.0.1', 49742)] ('127.0.0.1', 49742) is connected.
18/01/08 09:26:47 [INFO] 45 [('127.0.0.1', 49742)] Account: user02
18/01/08 09:26:47 [INFO] 60 [('127.0.0.1', 49742)] "user02" Auth success.
18/01/08 09:26:48 [DEBUG] 75 [('127.0.0.1', 49742)] Recive data length: b'3'
18/01/08 09:26:48 [INFO] 88 [('127.0.0.1', 49742)] Command: dir
18/01/08 09:26:48 [DEBUG] 102 [('127.0.0.1', 49742)] Action: _dir
18/01/08 09:26:50 [DEBUG] 75 [('127.0.0.1', 49742)] Recive data length: b'26'
18/01/08 09:26:50 [INFO] 88 [('127.0.0.1', 49742)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:26:50 [DEBUG] 102 [('127.0.0.1', 49742)] Action: _put
18/01/08 09:26:57 [WARNING] 125 [('127.0.0.1', 49742)] ('127.0.0.1', 49742) is disconnected.
18/01/08 09:27:00 [INFO] 41 [('127.0.0.1', 49743)] ('127.0.0.1', 49743) is connected.
18/01/08 09:27:00 [INFO] 45 [('127.0.0.1', 49743)] Account: user02
18/01/08 09:27:00 [INFO] 60 [('127.0.0.1', 49743)] "user02" Auth success.
18/01/08 09:27:01 [DEBUG] 75 [('127.0.0.1', 49743)] Recive data length: b'3'
18/01/08 09:27:01 [INFO] 88 [('127.0.0.1', 49743)] Command: dir
18/01/08 09:27:01 [DEBUG] 102 [('127.0.0.1', 49743)] Action: _dir
18/01/08 09:27:04 [DEBUG] 75 [('127.0.0.1', 49743)] Recive data length: b'26'
18/01/08 09:27:04 [INFO] 88 [('127.0.0.1', 49743)] Command: put python-3.6.3-amd64.exe 31619840
18/01/08 09:27:04 [DEBUG] 102 [('127.0.0.1', 49743)] Action: _put
18/01/08 09:27:10 [INFO] 169 [('127.0.0.1', 49743)] File md5 value is correct. [python-3.6.3-amd64.exe]
18/01/08 09:27:14 [DEBUG] 75 [('127.0.0.1', 49743)] Recive data length: b'3'
18/01/08 09:27:14 [INFO] 88 [('127.0.0.1', 49743)] Command: dir
18/01/08 09:27:14 [DEBUG] 102 [('127.0.0.1', 49743)] Action: _dir
18/01/08 09:27:26 [DEBUG] 75 [('127.0.0.1', 49743)] Recive data length: b'26'
18/01/08 09:27:26 [INFO] 88 [('127.0.0.1', 49743)] Command: get python-3.6.3-amd64.exe
18/01/08 09:27:26 [DEBUG] 102 [('127.0.0.1', 49743)] Action: _get
18/01/08 09:27:29 [ERROR] 196 [('127.0.0.1', 49743)] [WinError 10054] 远程主机强迫关闭了一个现有的连接。
18/01/08 09:27:29 [ERROR] 110 [('127.0.0.1', 49743)] [WinError 10054] 远程主机强迫关闭了一个现有的连接。
18/01/08 09:27:29 [WARNING] 125 [('127.0.0.1', 49743)] ('127.0.0.1', 49743) is disconnected.
18/01/08 09:27:36 [INFO] 41 [('127.0.0.1', 49744)] ('127.0.0.1', 49744) is connected.
18/01/08 09:27:36 [INFO] 45 [('127.0.0.1', 49744)] Account: user02
18/01/08 09:27:36 [INFO] 60 [('127.0.0.1', 49744)] "user02" Auth success.
18/01/08 09:27:37 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'3'
18/01/08 09:27:37 [INFO] 88 [('127.0.0.1', 49744)] Command: dir
18/01/08 09:27:37 [DEBUG] 102 [('127.0.0.1', 49744)] Action: _dir
18/01/08 09:27:39 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'26'
18/01/08 09:27:39 [INFO] 88 [('127.0.0.1', 49744)] Command: get python-3.6.3-amd64.exe
18/01/08 09:27:39 [DEBUG] 102 [('127.0.0.1', 49744)] Action: _get
18/01/08 09:27:44 [INFO] 191 [('127.0.0.1', 49744)] Transafer "D:\python_projects\training_bloke\module3\ftp\dirs\user02\python-3.6.3-amd64.exe" complete.
18/01/08 09:27:45 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'3'
18/01/08 09:27:45 [INFO] 88 [('127.0.0.1', 49744)] Command: dir
18/01/08 09:27:45 [DEBUG] 102 [('127.0.0.1', 49744)] Action: _dir
18/01/08 09:27:48 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'26'
18/01/08 09:27:48 [INFO] 88 [('127.0.0.1', 49744)] Command: del python-3.6.3-amd64.exe
18/01/08 09:27:48 [DEBUG] 102 [('127.0.0.1', 49744)] Action: _del
18/01/08 09:27:48 [DEBUG] 262 [('127.0.0.1', 49744)] Delete success: D:\python_projects\training_bloke\module3\ftp\dirs\user02\python-3.6.3-amd64.exe
18/01/08 09:27:49 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'3'
18/01/08 09:27:49 [INFO] 88 [('127.0.0.1', 49744)] Command: dir
18/01/08 09:27:49 [DEBUG] 102 [('127.0.0.1', 49744)] Action: _dir
18/01/08 09:27:51 [DEBUG] 75 [('127.0.0.1', 49744)] Recive data length: b'3'
18/01/08 09:27:51 [INFO] 88 [('127.0.0.1', 49744)] Command: 
18/01/08 09:27:51 [ERROR] 92 [('127.0.0.1', 49744)] list index out of range
18/01/08 09:27:51 [WARNING] 125 [('127.0.0.1', 49744)] ('127.0.0.1', 49744) is disconnected.
